use dev_itutor;
CREATE TABLE `school_data` (
  `school_id` int NOT NULL AUTO_INCREMENT,
  `school_no` int DEFAULT NULL,
  `category_eng` varchar(256) DEFAULT NULL,
  `category_zh` varchar(256) DEFAULT NULL,
  `school_name_eng` varchar(256) DEFAULT NULL,
  `school_name_zh` varchar(256) DEFAULT NULL,
  `school_address_eng` varchar(256) DEFAULT NULL,
  `school_address_zh` varchar(256) DEFAULT NULL,
  `longitude` varchar(256) DEFAULT NULL,
  `latitude` varchar(256) DEFAULT NULL,
  `easting` decimal(8,2) DEFAULT NULL,
  `northing` decimal(8,2) DEFAULT NULL,
  `student_gender_eng` varchar(45) DEFAULT NULL,
  `student_gender_zh` varchar(45) DEFAULT NULL,
  `school_session` varchar(45) DEFAULT NULL,
  `school_session_zh` varchar(45) DEFAULT NULL,
  `district_eng` varchar(45) DEFAULT NULL,
  `district_zh` varchar(45) DEFAULT NULL,
  `finance_type_eng` varchar(45) DEFAULT NULL,
  `finance_type_zh` varchar(45) DEFAULT NULL,
  `school_level_eng` varchar(45) DEFAULT NULL,
  `school_level_zh` varchar(45) DEFAULT NULL,
  `school_tel` varchar(45) DEFAULT NULL,
  `school_fax` varchar(45) DEFAULT NULL,
  `school_website` varchar(256) DEFAULT NULL,
  `RELIGION` varchar(256) DEFAULT NULL,
  `school_catholicism_zh` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`school_id`),
  UNIQUE KEY `school_id_UNIQUE` (`school_id`),
  UNIQUE KEY `school_no_UNIQUE` (`school_no`),
  UNIQUE KEY `school_tel_UNIQUE` (`school_tel`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci